language: node_js
node_js:
- '6'
script:
  - npm run test
  - npm run test:headless
addons:
  apt:
    packages:
      - xvfb
  sauce_connect:
    username: bredele
  jwt:
    secure: g6DIZATBChPcLETSG7FkxodAs2AoBK4NnRC4y9vcWqwOs0DZaFK2P0MfT8BRovcsybH1pywDwFaXR7+xRmjLHtZ8NiupoYJ4MWzBD4FbNwSI9TZkLWpapVNlWn966qJiyj2CyuAzU8wKaQYk7i52o76seAWhpgVHoyVqGl6OiiNM9btODyc/37xNP5Au2ZQkuU614y9/TaP0jkfPJ344FboYZAXv8gyXgAR/ghTZ8cXWtP+uX5n+b9K6x3fhjmA3xnxlD9s6b1532OLf1b6Qhs3+lkaNUqy+arOF898S5SBm/spFwHJFGbmH2EaKpU+GaM7VfFQvYcmGxzdGx0nMGvXpAfcYatqwuaYKv08ES4kaJLMoEvyFxxLtHXbpU581lKUAkYViNe+U0p7Q6NsvqeHH2TDkeQ9i5SKoSI2CXNs4Ev2eBduKd2a+wb8OJ2tSgNtr6j83pOSF75gL905T4n2WnqSZ0HY2otz1+Vt0PEJ0RJIJRqQ0lmGGTgiD4CyYemoNuCVxS7TrWSrXbiB1HS01LXqk00RoLOvN/RaoPJMqvIoeKUJ7bLmh8JHbM9CXPAu5fvh9zi8JQy6t5xikAM+WYoPPV8vP/REw46XBD4ss8QYu+FRc0kWpWoLhUlgzcJX2nZvnPHjFEdtZkd7jkX/jKd0XV42aCumBa1D9i44=
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
